import { useEffect, useMemo, useRef, useState } from "react";
import {
  ArrowLeft, ArrowRight, Bookmark, Check, ChevronDown, Copy, Lightbulb,
  Mail, Menu, Pencil, Plus, Send, Sparkles, Star, Trash2, X
} from "lucide-react";

type Idea = { id: number; title: string; text: string; category: string; favorite: boolean };
type Notebook = {
  path: string; styles: string[]; brainDump: string; why: string; problem: string;
  who: string; current: string; vision: string; partners: string; nextStep: string;
  when: string; roadblocks: string[]; perspective: string; change: string;
  ideas: Idea[]; selected: number[];
};

const freshNotebook: Notebook = {
  path: "", styles: [], brainDump: "", why: "", problem: "", who: "", current: "",
  vision: "", partners: "", nextStep: "", when: "", roadblocks: [], perspective: "",
  change: "", ideas: [], selected: [],
};

const pages = [
  { id: "start", label: "Start here" }, { id: "dump", label: "Brain dump" },
  { id: "why", label: "The why" }, { id: "problem", label: "The problem" },
  { id: "explore", label: "Explore" }, { id: "ideas", label: "Idea wall" },
  { id: "focus", label: "Find focus" }, { id: "vision", label: "Imagine it" },
  { id: "next", label: "Next step" }, { id: "summary", label: "Summary" },
];
const paths = ["I have an idea", "I want to start something", "I want to solve a problem", "I want to improve something", "I have several ideas", "I know what I want but don't know where to start", "I'm not sure yet. Help me brainstorm"];
const styles = [
  ["Big Picture", "I see where I want to go. Help me work backward."], ["Step by Step", "Give me structure and help me figure it out piece by piece."],
  ["Question Me", "Ask me questions until the idea becomes clearer."], ["Rapid Fire", "Give me prompts and let me throw ideas at the page."],
  ["Problem Solver", "Start with the problem and help me find possible solutions."], ["Storyteller", "Let me explain what I'm imagining in my own words."],
  ["Visual Thinker", "Help me organize ideas visually."], ["Dream Mode", "Forget limitations for a minute. Let me imagine what this might become."],
];
const prompts = ["What would surprise you?", "What would make this much simpler?", "Who else might see this differently?", "What are you not saying yet?", "How might we make this ten times bigger?", "What would you try with only $100?", "How might we remove the biggest obstacle?"];
const perspectives = ["The Customer", "The Beginner", "The Expert", "The Skeptic", "The Child", "The Investor", "The Competitor", "The Community", "The Future You"];
const roadblocks = ["I don't know where to start", "Money", "Technology", "Time", "Knowledge", "Marketing", "Design", "Finding customers", "Finding partners", "Confidence", "Team", "Too many ideas", "I'm doing this alone", "Something else"];
const categories = ["Love this", "Explore this", "Question", "Problem", "Opportunity", "Needs research", "Later"];
const key = "lets-soar-creative-notebook";

const ProjectNotebook = () => {
  const [page, setPage] = useState("start");
  const [book, setBook] = useState<Notebook>(freshNotebook);
  const [draftIdea, setDraftIdea] = useState("");
  const [saved, setSaved] = useState(false);
  const [prompt, setPrompt] = useState("");
  const [showContact, setShowContact] = useState(false);
  const [menuOpen, setMenuOpen] = useState(false);
  const [isRevealed, setIsRevealed] = useState(false);
  const notebookRef = useRef<HTMLElement>(null);

  useEffect(() => {
    const node = notebookRef.current;
    if (!node || typeof IntersectionObserver === "undefined") { setIsRevealed(true); return; }
    const observer = new IntersectionObserver(([entry]) => { if (entry.isIntersecting) { setIsRevealed(true); observer.disconnect(); } }, { threshold: 0.18 });
    observer.observe(node);
    return () => observer.disconnect();
  }, []);
  useEffect(() => { try { const savedBook = localStorage.getItem(key); if (savedBook) setBook({ ...freshNotebook, ...JSON.parse(savedBook) }); } catch { /* a clean notebook is a good fallback */ } }, []);
  useEffect(() => { localStorage.setItem(key, JSON.stringify(book)); setSaved(true); const timer = window.setTimeout(() => setSaved(false), 1600); return () => window.clearTimeout(timer); }, [book]);
  const update = (field: keyof Notebook, value: string | string[] | number[] | Idea[]) => setBook((current) => ({ ...current, [field]: value }));
  const pageIndex = pages.findIndex((item) => item.id === page);
  const go = (id: string) => { setPage(id); setMenuOpen(false); window.setTimeout(() => document.querySelector(".notebook-stage")?.scrollIntoView({ behavior: "smooth", block: "start" }), 0); };
  const next = () => go(pages[Math.min(pageIndex + 1, pages.length - 1)].id);
  const back = () => go(pages[Math.max(pageIndex - 1, 0)].id);
  const saveCard = () => { if (!draftIdea.trim()) return; setBook((current) => ({ ...current, ideas: [...current.ideas, { id: Date.now(), title: draftIdea.trim().split(/[.!?]/)[0].slice(0, 42), text: draftIdea.trim(), category: "Explore this", favorite: false }] })); setDraftIdea(""); };
  const selectedIdeas = useMemo(() => book.ideas.filter((idea) => book.selected.includes(idea.id)), [book.ideas, book.selected]);
  const toggleRoadblock = (item: string) => update("roadblocks", book.roadblocks.includes(item) ? book.roadblocks.filter((x) => x !== item) : [...book.roadblocks, item]);
  const toggleStyle = (item: string) => update("styles", book.styles.includes(item) ? book.styles.filter((x) => x !== item) : [...book.styles, item]);
  const toggleIdea = (id: number) => update("selected", book.selected.includes(id) ? book.selected.filter((x) => x !== id) : [...book.selected, id]);
  const stuck = () => { setPrompt(prompts[Math.floor(Math.random() * prompts.length)]); if (!prompt) return; };
  const updateIdea = (id: number, patch: Partial<Idea>) => update("ideas", book.ideas.map((idea) => idea.id === id ? { ...idea, ...patch } : idea));

  const pageTitle = pages.find((item) => item.id === page)?.label;
  return <section ref={notebookRef} id="project-notebook" className={`creative-notebook ${isRevealed ? "is-revealed" : ""}`}>
    <div className="notebook-wrap">
      <header className="notebook-header">
        <div className="notebook-brand"><span className="notebook-mark"><BookIcon /></span><div><span className="eyebrow">Project Notebook</span><strong>Your ideas, in progress.</strong></div></div>
        <div className="notebook-status"><span className={`save-dot ${saved ? "is-saving" : ""}`} /> {saved ? "Saved privately" : "Saved on this device"} <button className="notebook-menu" onClick={() => setMenuOpen(!menuOpen)} aria-label="Open notebook pages"><Menu size={18} /></button></div>
      </header>
      {menuOpen && <nav className="notebook-menu-panel">{pages.map((item, index) => <button key={item.id} className={item.id === page ? "active" : ""} onClick={() => go(item.id)}><span>{String(index + 1).padStart(2, "0")}</span>{item.label}</button>)}</nav>}
      <div className="notebook-progress"><div style={{ width: `${Math.max(8, ((pageIndex + 1) / pages.length) * 100)}%` }} /></div>

      <div className="notebook-layout">
        <aside className="notebook-sidebar"><div className="side-label">Your pages</div>{pages.map((item, index) => <button key={item.id} onClick={() => go(item.id)} className={item.id === page ? "active" : ""}><span>{index < pageIndex ? <Check size={13} /> : String(index + 1).padStart(2, "0")}</span>{item.label}</button>)}<div className="private-note"><Bookmark size={15} /><strong>Private by default</strong><small>Your notebook stays on this device unless you choose to share it.</small></div></aside>
        <main className="notebook-stage">
          <div className="page-kicker"><span>Page {String(pageIndex + 1).padStart(2, "0")}</span><span>{pageTitle}</span></div>
          {page === "start" && <StartPage book={book} update={update} go={go} />}
          {page === "dump" && <><PageIntro eyebrow="Make a little room in your head" title="Brain Dump" text="Forget grammar, organization, and whether it makes sense yet. Write down everything you're thinking." /><div className="dont-judge"><Sparkles size={16} /> Don't judge the idea yet. Put it on the page first.</div><textarea className="notebook-writing huge" value={book.brainDump} onChange={(e) => update("brainDump", e.target.value)} placeholder="Start anywhere... a feeling, a question, a half-formed thought..." />{prompt && <div className="prompt-card"><Sparkles size={17} /><span>{prompt}</span><button onClick={() => setPrompt("")}><X size={15} /></button></div>}<div className="prompt-actions">{["Ask me a question", "Give me another angle", "Challenge my thinking", "Make me think bigger", "Make me simplify it", "What am I missing?", "Give me a crazy question"].map((item) => <button key={item} onClick={() => setPrompt(prompts[Math.floor(Math.random() * prompts.length)])}>{item}</button>)}</div><div className="card-capture"><div><span className="eyebrow">See something worth keeping?</span><strong>Save a thought to your Idea Wall</strong></div><div className="inline-capture"><input value={draftIdea} onChange={(e) => setDraftIdea(e.target.value)} placeholder="A thought worth remembering..." /><button onClick={saveCard}><Plus size={16} /> Save idea</button></div></div></>}
          {page === "why" && <><PageIntro eyebrow="Follow the energy" title="Why does this matter to you?" text="You don't need the perfect answer. Follow the thread that feels most alive." /><Question label="What made you think about it in the first place?" value={book.why} onChange={(v) => update("why", v)} /><Question label="Who would this help?" value={book.who} onChange={(v) => update("who", v)} /><Question label="If this worked exactly the way you imagine, what would change?" value={book.current} onChange={(v) => update("current", v)} /></>}
          {page === "problem" && <><PageIntro eyebrow="Look a little closer" title="What are we really solving?" text="Start with the tension. Solutions can come later." /><Question label="What problem are you trying to solve?" value={book.problem} onChange={(v) => update("problem", v)} /><Question label="How are people solving it now, and what frustrates you about that?" value={book.change} onChange={(v) => update("change", v)} /><div className="why-box"><strong>Try the Five Whys</strong><p>Choose something you wrote, then ask: <em>Why does that matter?</em> Keep going only while it helps.</p><button className="text-button" onClick={() => setPrompt("Why does that matter?")}>Start with a why <ArrowRight size={15} /></button></div></>}
          {page === "explore" && <ExplorePage book={book} update={update} perspectives={perspectives} prompt={prompt} setPrompt={setPrompt} />}
          {page === "ideas" && <IdeasPage book={book} draftIdea={draftIdea} setDraftIdea={setDraftIdea} saveCard={saveCard} updateIdea={updateIdea} toggleIdea={toggleIdea} />}
          {page === "focus" && <><PageIntro eyebrow="A little clarity, when you're ready" title="What deserves your attention?" text="You've generated some ideas. Now let's see what deserves your attention. Pick up to three—there's no wrong choice." />{book.ideas.length === 0 ? <EmptyIdeas onClick={() => go("dump")} /> : <div className="idea-grid">{book.ideas.map((idea) => <button key={idea.id} className={`focus-card ${book.selected.includes(idea.id) ? "chosen" : ""}`} onClick={() => toggleIdea(idea.id)}><span>{book.selected.includes(idea.id) ? <Check size={15} /> : <span className="circle" />}</span><strong>{idea.title}</strong><p>{idea.text}</p></button>)}</div>} {selectedIdeas.length > 0 && <div className="selected-reflection"><span className="eyebrow">For the ideas you've picked</span><Question label="What is the smallest version you could start with?" value={book.nextStep} onChange={(v) => update("nextStep", v)} compact /><Question label="What is the biggest unknown?" value={book.change} onChange={(v) => update("change", v)} compact /></div>}</>}
          {page === "vision" && <><PageIntro eyebrow="Let yourself see it" title="Imagine it worked" text="It is three years from now and this worked. What happened?" /><Question label="What does it look like? Who is involved? Who did it help?" value={book.vision} onChange={(v) => update("vision", v)} large /><div className="sentence-builder"><span className="eyebrow">My idea in one sentence</span><p>I want to <input placeholder="..." /> for <input placeholder="..." /> because <input placeholder="..." />.</p><textarea value={book.current} onChange={(e) => update("current", e.target.value)} placeholder="Rewrite it in your own words if you like..." /></div></>}
          {page === "next" && <><PageIntro eyebrow="Make it yours" title="What's in the way?" text="Naming a roadblock can make it feel a little more workable. Pick anything that feels true." /><div className="choice-grid">{roadblocks.map((item) => <button key={item} className={book.roadblocks.includes(item) ? "selected" : ""} onClick={() => toggleRoadblock(item)}>{book.roadblocks.includes(item) && <Check size={15} />}{item}</button>)}</div><div className="partnership"><PageIntro eyebrow="You don't have to build alone" title="Who would help this idea grow?" text="What do you already do well? What part would you rather not do yourself?" /><textarea className="notebook-writing" value={book.partners} onChange={(e) => update("partners", e.target.value)} placeholder="A designer, developer, strategist, mentor... or someone who just gets it." /><div className="next-step"><span className="eyebrow">One small step</span><Question label="What is one thing you could do next?" value={book.nextStep} onChange={(v) => update("nextStep", v)} compact /><div className="choice-row">{["Today", "This week", "This month", "I'm still thinking"].map((item) => <button key={item} className={book.when === item ? "selected" : ""} onClick={() => update("when", item)}>{item}</button>)}</div></div></div></>}
          {page === "summary" && <Summary book={book} onShare={() => { setShowContact(true); }} />}
          {showContact && <ContactPanel onClose={() => setShowContact(false)} book={book} />}
          {page !== "summary" && <div className="notebook-nav"><button onClick={back} disabled={pageIndex === 0}><ArrowLeft size={16} /> Back</button><button className="stuck" onClick={stuck}><Sparkles size={15} /> I'm stuck</button><button className="next-button" onClick={next}>{pageIndex === pages.length - 1 ? "Finish" : "Keep going"}<ArrowRight size={16} /></button></div>}
        </main>
      </div>
    </div>
  </section>;
};

const BookIcon = () => <span className="book-icon">✦</span>;
const PageIntro = ({ eyebrow, title, text }: { eyebrow: string; title: string; text: string }) => <div className="page-intro"><span className="eyebrow">{eyebrow}</span><h2>{title}</h2><p>{text}</p></div>;
const Question = ({ label, value, onChange, large = false, compact = false }: { label: string; value: string; onChange: (value: string) => void; large?: boolean; compact?: boolean }) => <label className={`notebook-question ${large ? "large" : ""} ${compact ? "compact" : ""}`}><span>{label}</span><textarea value={value} onChange={(e) => onChange(e.target.value)} placeholder="Write whatever comes to mind..." /></label>;
const StartPage = ({ book, update, go }: { book: Notebook; update: (field: keyof Notebook, value: string | string[] | number[] | Idea[]) => void; go: (id: string) => void }) => <><PageIntro eyebrow="A quiet place to think" title="What's been on your mind?" text="Everyone has ideas. Some have been sitting in your head for days. Others have been there for years. This notebook gives you a place to get them out of your head, explore them, organize them, and decide what you want to do next." /><div className="start-block"><h3>What would you like to explore today?</h3><div className="path-grid">{paths.map((path) => <button key={path} className={book.path === path ? "selected" : ""} onClick={() => update("path", path)}>{book.path === path && <Check size={15} />}{path}</button>)}</div></div><div className="start-block style-block"><h3>How do you like to think?</h3><p className="helper">Choose one or several. This helps shape the prompts that follow.</p><div className="style-list">{styles.map(([title, text]) => <button key={title} className={book.styles.includes(title) ? "selected" : ""} onClick={() => update("styles", book.styles.includes(title) ? book.styles.filter((x) => x !== title) : [...book.styles, title])}><span className="style-check">{book.styles.includes(title) ? <Check size={14} /> : <Lightbulb size={14} />}</span><span><strong>{title}</strong><small>{text}</small></span></button>)}</div><button className="start-cta" onClick={() => go("dump")}>Open my notebook <ArrowRight size={17} /></button></div></>;
const ExplorePage = ({ book, update, perspectives, prompt, setPrompt }: { book: Notebook; update: (field: keyof Notebook, value: string | string[] | number[] | Idea[]) => void; perspectives: string[]; prompt: string; setPrompt: (value: string) => void }) => <><PageIntro eyebrow="Change the angle" title="Look at it differently" text="Sometimes a new perspective unlocks something that was already there." /><div className="perspective-pills">{perspectives.map((item) => <button key={item} className={book.perspective === item ? "selected" : ""} onClick={() => update("perspective", item)}>{item}</button>)}</div><Question label={book.perspective ? `What would ${book.perspective.toLowerCase()} notice, question, or change?` : "Choose a perspective, then write what it sees."} value={book.perspective === "" ? "" : book.change} onChange={(v) => update("change", v)} large /><div className="change-idea"><PageIntro eyebrow="Optional" title="Change the idea" text="What might you substitute, combine, adapt, modify, eliminate, or reverse?" /><button className="push-button" onClick={() => setPrompt(prompts[Math.floor(Math.random() * prompts.length)])}><Sparkles size={16} /> Push my thinking</button>{prompt && <div className="prompt-card"><Sparkles size={17} /><span>{prompt}</span></div>}</div></>;
const IdeasPage = ({ book, draftIdea, setDraftIdea, saveCard, updateIdea, toggleIdea }: { book: Notebook; draftIdea: string; setDraftIdea: (value: string) => void; saveCard: () => void; updateIdea: (id: number, patch: Partial<Idea>) => void; toggleIdea: (id: number) => void }) => <><PageIntro eyebrow="Thoughts worth keeping" title="Your Idea Wall" text="Save individual thoughts as cards. Move them around, notice connections, and let the good ones find you again." /><div className="idea-capture"><input value={draftIdea} onChange={(e) => setDraftIdea(e.target.value)} onKeyDown={(e) => e.key === "Enter" && saveCard()} placeholder="Add an idea card..." /><button onClick={saveCard}><Plus size={16} /> Add card</button></div>{book.ideas.length === 0 ? <EmptyIdeas /> : <div className="idea-wall">{book.ideas.map((idea) => <article className="idea-card" key={idea.id}><div className="idea-card-top"><button onClick={() => updateIdea(idea.id, { favorite: !idea.favorite })} aria-label="Favorite idea"><Star size={17} fill={idea.favorite ? "currentColor" : "none"} /></button><button onClick={() => updateIdea(idea.id, { text: `${idea.text} ` })} aria-label="Edit idea"><Pencil size={15} /></button><button onClick={() => updateIdea(idea.id, { text: "" })} aria-label="Clear idea"><Trash2 size={15} /></button></div><input className="idea-title" value={idea.title} onChange={(e) => updateIdea(idea.id, { title: e.target.value })} /><textarea value={idea.text} onChange={(e) => updateIdea(idea.id, { text: e.target.value })} /><select value={idea.category} onChange={(e) => updateIdea(idea.id, { category: e.target.value })}>{categories.map((category) => <option key={category}>{category}</option>)}</select><button className={`card-select ${book.selected.includes(idea.id) ? "selected" : ""}`} onClick={() => toggleIdea(idea.id)}>{book.selected.includes(idea.id) ? <Check size={14} /> : <Copy size={14} />} {book.selected.includes(idea.id) ? "Picked for focus" : "Pick for focus"}</button></article>)}</div>}</>;
const EmptyIdeas = ({ onClick }: { onClick?: () => void }) => <div className="empty-ideas"><Lightbulb size={28} /><strong>Your wall is waiting.</strong><p>Save a thought from your Brain Dump and it will land here.</p>{onClick && <button onClick={onClick}>Go to Brain Dump <ArrowRight size={15} /></button>}</div>;
const Summary = ({ book, onShare }: { book: Notebook; onShare: () => void }) => <><div className="print-notebook-heading"><span>Project Notebook</span><strong>My ideas, in progress.</strong><small>Private working notes · {new Date().toLocaleDateString()}</small></div><PageIntro eyebrow="A snapshot of your thinking" title="Your Notebook Summary" text="This is yours to keep, revisit, and reshape. Nothing here needs to be finished." /><div className="summary-paper"><SummaryItem title="My idea" text={book.brainDump || "Still taking shape..."} /><SummaryItem title="Why it matters" text={book.why || "You haven't written this part yet."} /><SummaryItem title="The problem & who it helps" text={[book.problem, book.who].filter(Boolean).join(" — ") || "Still exploring..."} /><SummaryItem title="Ideas I want to explore" text={book.ideas.map((idea) => idea.title).join(", ") || "Your Idea Wall is waiting."} /><SummaryItem title="What I need" text={book.roadblocks.join(", ") || "Not named yet."} /><SummaryItem title="My first step" text={book.nextStep || "A next step will appear when you're ready."} /></div><div className="summary-actions"><button className="keep-button" onClick={() => window.print()}><Bookmark size={16} /> Print notebook / save as PDF</button><button className="share-button" onClick={onShare}><Send size={16} /> Let's talk about it</button></div></>;
const SummaryItem = ({ title, text }: { title: string; text: string }) => <div><span>{title}</span><p>{text}</p></div>;
const ContactPanel = ({ onClose, book }: { onClose: () => void; book: Notebook }) => { const [sent, setSent] = useState(false); const [name, setName] = useState(""); const [email, setEmail] = useState(""); const [phone, setPhone] = useState(""); const [preferred, setPreferred] = useState("Email"); const send = () => { const body = `Name: ${name}\nEmail: ${email}\nPhone: ${phone}\nPreferred contact: ${preferred}\n\nNotebook:\n${book.brainDump}`; window.location.href = `mailto:hello@letssoartogether.com?subject=${encodeURIComponent("My Project Notebook")}&body=${encodeURIComponent(body)}`; setSent(true); }; return <div className="contact-overlay"><div className="contact-panel"><button className="close-panel" onClick={onClose}><X size={20} /></button>{sent ? <><div className="sent-mark"><Check size={25} /></div><PageIntro eyebrow="Thank you" title="Your notebook is on its way." text="We'll read what you've shared and start a thoughtful conversation." /></> : <><PageIntro eyebrow="Only if you choose" title="What would you like to do with your notebook?" text="Your notebook stays yours. Sending it simply gives our team permission to read what you've shared and start a conversation with you." /><label>Name<input value={name} onChange={(e) => setName(e.target.value)} placeholder="Your name" /></label><label>Email<input type="email" value={email} onChange={(e) => setEmail(e.target.value)} placeholder="you@example.com" /></label><label>Phone <span>(optional)</span><input value={phone} onChange={(e) => setPhone(e.target.value)} placeholder="" /></label><label>Preferred way to contact you<select value={preferred} onChange={(e) => setPreferred(e.target.value)}><option>Email</option><option>Phone</option><option>Either is fine</option></select></label><button className="send-notebook" onClick={send} disabled={!name || !email}><Mail size={16} /> Send my notebook to Aquila</button><button className="cancel-share" onClick={onClose}>Keep it for myself</button></>}</div></div>; };

export default ProjectNotebook;
